# Generated by Django 2.2.4 on 2022-06-25 08:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AA_Login',
            new_name='CA_Login',
        ),
        migrations.DeleteModel(
            name='CUA_Login',
        ),
        migrations.RemoveField(
            model_name='file_request',
            name='cua_private_key',
        ),
        migrations.RemoveField(
            model_name='file_request',
            name='cua_public_key',
        ),
        migrations.AlterField(
            model_name='upload_file',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 25, 8, 20, 17, 193189, tzinfo=utc), verbose_name='Uploaded Date'),
        ),
    ]
