# Generated by Django 3.2 on 2022-12-12 04:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220625_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_file',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 12, 4, 29, 15, 525832, tzinfo=utc), verbose_name='Uploaded Date'),
        ),
        migrations.CreateModel(
            name='File_Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(blank=True, max_length=1000, null=True, verbose_name='keywords')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.upload_file')),
            ],
        ),
    ]
